export const companies = [
  {
    name: 'Graffersid Web and App Development',
    address: '© 916, Shekhar Central, Manorama Ganj, AB road, New Palasia, Indore (M.P.)',
    founded: '01-01-2018',
    rating: 4.5,
    reviews: 41,
    logo: 'G',
  },
  {
    name: 'Code Tech Company',
    address: '© 414, Kanha Appartment, Bhawarkua, Indore (M.P.)',
    founded: '01-01-2016',
    rating: 4.5,
    reviews: 38,
    logo: 'CT',
  },
  {
    name: 'Innogen Pvt. Ltd.',
    address: '© 910, Shekhar Central, Manorama Ganj, Indore (M.P.)',
    founded: '01-01-2016',
    rating: 4.5,
    reviews: 25,
    logo: '💡',
  },
  {
    name: 'Pixel Web and App Development',
    address: '© 410, Bansi Trade Center, Indore (M.P.)',
    founded: '01-01-2016',
    rating: 4.5,
    reviews: 51,
    logo: 'P',
  },
  {
    name: 'Innogen Pvt. Ltd.',
    address: '© 910, Shekhar Central, Manorama Ganj, Indore (M.P.)',
    founded: '01-01-2016',
    rating: 4.5,
    reviews: 25,
    logo: '💡',
  },
  {
    name: 'Pixel Web and App Development',
    address: '© 410, Bansi Trade Center, Indore (M.P.)',
    founded: '01-01-2016',
    rating: 4.5,
    reviews: 51,
    logo: 'P',
  },
];
